// composables/types.ts
export interface CalendarEvent {
  id: string
  title: string
  description?: string
  startDate: Date
  endDate: Date
  startTime?: string
  endTime?: string
  allDay?: boolean
  color?: EventColor
  location?: string
  // Recurring event support
  isRecurring?: boolean
  recurringPattern?: RecurringPattern
  recurringId?: string // Links recurring instances
}

export interface RecurringPattern {
  type: 'daily' | 'weekly' | 'monthly' | 'yearly'
  interval: number // Every N days/weeks/months/years
  endDate?: Date
  count?: number // Number of occurrences
  daysOfWeek?: number[] // For weekly: 0=Sunday, 1=Monday, etc.
  dayOfMonth?: number // For monthly
  monthOfYear?: number // For yearly
}

export type ViewMode = "month" | "week" | "day" | "agenda"

// For passing pre-calculated day data to MonthView
export interface MonthViewDay {
  date: Date
  isCurrentMonth: boolean
  isToday: boolean
  events: CalendarEvent[] // Events specific to this day in month view
}

// For WeekView and DayView structure
export interface TimeSlot {
  time: Date
  label: string
  dateTimeStr: string // For data attributes, e.g., clicking to add
}

export interface DayColumnData {
  date: Date
  dateKey: string // 'yyyy-MM-dd'
  dayLabel?: string // For WeekView, e.g., 'Mon 01'
  isToday: boolean
  allDayEvents: CalendarEvent[]
  timeSlots?: TimeSlot[] // Optional since it's generated by view components
  // Timed events will be processed with style by the view component
  timedEventsRaw: CalendarEvent[]
}

export type EventColor = "sky" | "amber" | "violet" | "rose" | "emerald" | "orange"

// Location Display Types
export interface LocationDisplayProps {
  location?: string
  showIcon?: boolean
  showTooltip?: boolean
  compact?: boolean
  iconSize?: number
}

export interface LocationData {
  address: string
  coordinates?: { lat: number; lng: number }
  placeId?: string // For future Google Places integration
}
